rule CVE_2011_4114
{
//This rule was generated by: ./yargen -m PAR::Packer -c CVE-2011-4114
	meta:
		component_name = "PAR-Packer module for Perl"
		component_version = "before 1.012"
		custom_title = "Roderich Schupp Par-packer Module up to 0.71 PAR::Packer unknown vulnerability"
		custom_level = "low"
		custom_description = "<p>The par_mktmpdir function in the PAR::Packer module before 1.012 for Perl creates temporary files in a directory with a predictable name without verifying ownership and permissions of this directory, which allows local users to overwrite files when another user extracts a PAR packed program. NOTE: a similar vulnerability was reported for PAR, but this has been assigned a different CVE identifier.</p>"
	strings:
		$v_1_011    = /our\s+\$VERSION\s*=\s*(\'|\")1.011(\'|\")\s*;/
		$v_1_010    = /our\s+\$VERSION\s*=\s*(\'|\")1.010(\'|\")\s*;/
		$v_1_009    = /our\s+\$VERSION\s*=\s*(\'|\")1.009(\'|\")\s*;/
		$v_1_008    = /our\s+\$VERSION\s*=\s*(\'|\")1.008(\'|\")\s*;/
		$v_1_007    = /our\s+\$VERSION\s*=\s*(\'|\")1.007(\'|\")\s*;/
		$v_1_006    = /our\s+\$VERSION\s*=\s*(\'|\")1.006(\'|\")\s*;/
		$v_1_005    = /our\s+\$VERSION\s*=\s*(\'|\")1.005(\'|\")\s*;/
		$v_1_004    = /our\s+\$VERSION\s*=\s*(\'|\")1.004(\'|\")\s*;/
		$v_1_003    = /our\s+\$VERSION\s*=\s*(\'|\")1.003(\'|\")\s*;/
		$v_1_002    = /our\s+\$VERSION\s*=\s*(\'|\")1.002(\'|\")\s*;/
		$v_1_001    = /our\s+\$VERSION\s*=\s*(\'|\")1.001(\'|\")\s*;/
		$v_1_000    = /our\s+\$VERSION\s*=\s*(\'|\")1.000(\'|\")\s*;/
	condition:
		PerlPARPackerModule and any of ($v*)
}
