rule CVE_2013_2145
{
//This rule was generated by: ./yargen -m Module::Signature -c CVE-2013-2145
	meta:
		component_name = "Module-Signature module for Perl"
		component_version = "before 0.72"
		custom_title = "Perl 0.70/0.71 CPAN Module::Signature Module buffer overflow"
		custom_level = "medium"
		custom_description = "<p>The cpansign verify functionality in the Module::Signature module before 0.72 for Perl allows attackers to bypass the signature check and execute arbitrary code via a SIGNATURE file with a 'special unknown cipher' that references an untrusted module in Digest/.</p>"
	strings:
		$v_0_71 = /\$Module::Signature::VERSION\s*=\s*(\'|\")0.71(\'|\")\s*;/
		$v_0_70 = /\$Module::Signature::VERSION\s*=\s*(\'|\")0.70(\'|\")\s*;/
	condition:
		PerlModuleSignatureModule and any of ($v*)
}
