rule CVE_2015_8949
{
//This rule was generated by: ./yargen -m DBD::mysql -c CVE-2015-8949
	meta:
		component_name = "DBD-mysql module for Perl"
		component_version = "before 4.033_01"
		custom_title = "DBD::mysql up to 4.033 my_login buffer overflow"
		custom_level = "medium"
		custom_description = "<p>Use-after-free vulnerability in the my_login function in DBD::mysql before 4.033_01 allows attackers to have unspecified impact by leveraging a call to mysql_errno after a failure of my_login.</p>"
	strings:
		$v_4_033    = /our\s+\$VERSION\s*=\s*(\'|\")4.033(\'|\")\s*;/
		$v_4_032_03 = /our\s+\$VERSION\s*=\s*(\'|\")4.032_03(\'|\")\s*;/
		$v_4_032_01 = /our\s+\$VERSION\s*=\s*(\'|\")4.032_01(\'|\")\s*;/
		$v_4_032    = /our\s+\$VERSION\s*=\s*(\'|\")4.032(\'|\")\s*;/
		$v_4_031    = /our\s+\$VERSION\s*=\s*(\'|\")4.031(\'|\")\s*;/
		$v_4_030_02 = /our\s+\$VERSION\s*=\s*(\'|\")4.030_02(\'|\")\s*;/
		$v_4_030_01 = /our\s+\$VERSION\s*=\s*(\'|\")4.030_01(\'|\")\s*;/
		$v_4_029    = /our\s+\$VERSION\s*=\s*(\'|\")4.029(\'|\")\s*;/
		$v_4_028    = /our\s+\$VERSION\s*=\s*(\'|\")4.028(\'|\")\s*;/
		$v_4_027    = /our\s+\$VERSION\s*=\s*(\'|\")4.027(\'|\")\s*;/
		$v_4_026    = /our\s+\$VERSION\s*=\s*(\'|\")4.026(\'|\")\s*;/
		$v_4_025    = /our\s+\$VERSION\s*=\s*(\'|\")4.025(\'|\")\s*;/
		$v_4_024    = /\$VERSION\s*=\s*(\'|\")4.024(\'|\")\s*;/
		$v_4_023    = /\$VERSION\s*=\s*(\'|\")4.023(\'|\")\s*;/
		$v_4_022    = /\$VERSION\s*=\s*(\'|\")4.022(\'|\")\s*;/
		$v_4_021    = /\$VERSION\s*=\s*(\'|\")4.021(\'|\")\s*;/
		$v_4_020    = /\$VERSION\s*=\s*(\'|\")4.020(\'|\")\s*;/
		$v_4_019    = /\$VERSION\s*=\s*(\'|\")4.019(\'|\")\s*;/
		$v_4_018    = /\$VERSION\s*=\s*(\'|\")4.018(\'|\")\s*;/
		$v_4_017    = /\$VERSION\s*=\s*(\'|\")4.017(\'|\")\s*;/
		$v_4_016    = /\$VERSION\s*=\s*(\'|\")4.016(\'|\")\s*;/
		$v_4_015    = /\$VERSION\s*=\s*(\'|\")4.015(\'|\")\s*;/
		$v_4_014    = /\$VERSION\s*=\s*(\'|\")4.014(\'|\")\s*;/
		$v_4_013    = /\$VERSION\s*=\s*(\'|\")4.013(\'|\")\s*;/
		$v_4_012    = /\$VERSION\s*=\s*(\'|\")4.012(\'|\")\s*;/
		$v_4_011    = /\$VERSION\s*=\s*(\'|\")4.011(\'|\")\s*;/
		$v_4_010    = /\$VERSION\s*=\s*(\'|\")4.010(\'|\")\s*;/
		$v_4_009    = /\$VERSION\s*=\s*(\'|\")4.009(\'|\")\s*;/
		$v_4_008    = /\$VERSION\s*=\s*(\'|\")4.008(\'|\")\s*;/
		$v_4_007    = /\$VERSION\s*=\s*(\'|\")4.007(\'|\")\s*;/
		$v_4_006    = /\$VERSION\s*=\s*(\'|\")4.006(\'|\")\s*;/
		$v_4_005    = /\$VERSION\s*=\s*(\'|\")4.005(\'|\")\s*;/
		$v_4_004    = /\$VERSION\s*=\s*(\'|\")4.004(\'|\")\s*;/
		$v_4_003    = /\$VERSION\s*=\s*(\'|\")4.003(\'|\")\s*;/
		$v_4_002    = /\$VERSION\s*=\s*(\'|\")4.002(\'|\")\s*;/
		$v_4_001    = /\$VERSION\s*=\s*4.001\s*;/
		$v_4_00     = /\$VERSION\s*=\s*(\'|\")4.00(\'|\")\s*;/
	condition:
		PerlDBDmysqlModule and any of ($v*)
}
