rule CVE_2013_7135
{
//This rule was generated by: ./yargen -m Proc::Daemon -c CVE-2013-7135
	meta:
		component_name = "Proc-Daemon module for Perl"
		component_version = "0.14"
		custom_title = "Detlef Pilzecker Proc::Daemon module 0.14 unknown vulnerability"
		custom_level = "medium"
		custom_description = "<p>The Proc::Daemon module 0.14 for Perl uses world-writable permissions for a file that stores a process ID, which allows local users to have an unspecified impact by modifying this file.</p>"
	strings:
		$v_0_14 = /\$Proc::Daemon::VERSION\s*=\s*(\'|\")0.14(\'|\")\s*;/
	condition:
		PerlProcDaemonModule and any of ($v*)
}
