rule CVE_2011_4363
{
//This rule was generated by: ./yargen -m Proc::ProcessTable -c CVE-2011-4363
	meta:
		component_name = "Proc-ProcessTable module for Perl"
		component_version = "0.45"
		custom_title = "Frii Proc::ProcessTable 0.45 privilege escalation"
		custom_level = "low"
		custom_description = "<p>ProcessTable.pm in the Proc::ProcessTable module 0.45 for Perl, when TTY information caching is enabled, allows local users to overwrite arbitrary files via a symlink attack on /tmp/TTYDEVS.</p>"
	strings:
		$v_0_45    = /\$VERSION\s*=\s*(\'|\")0.45(\'|\")\s*;/
	condition:
		PerlProcProcessTableModule and any of ($v*)
}
