rule CVE_2012_5526
{
//This rule was generated by: ./yargen -m CGI -c CVE-2012-5526
	meta:
		component_name = "CGI module for Perl"
		component_version = "before 3.63"
		custom_title = "Andy Armstrong CGI.pm 3.62 unknown vulnerability"
		custom_level = "low"
		custom_description = "<p>CGI.pm module before 3.63 for Perl does not properly escape newlines in (1) Set-Cookie or (2) P3P headers, which might allow remote attackers to inject arbitrary headers into responses from applications that use CGI.pm.</p>"
	strings:
		$v_3_62    = /\$CGI::VERSION\s*=\s*(\'|\")3.62(\'|\")\s*;/
		$v_3_61    = /\$CGI::VERSION\s*=\s*(\'|\")3.61(\'|\")\s*;/
		$v_3_60    = /\$CGI::VERSION\s*=\s*(\'|\")3.60(\'|\")\s*;/
		$v_3_59    = /\$CGI::VERSION\s*=\s*(\'|\")3.59(\'|\")\s*;/
		$v_3_58    = /\$CGI::VERSION\s*=\s*(\'|\")3.58(\'|\")\s*;/
		$v_3_57    = /\$CGI::VERSION\s*=\s*(\'|\")3.57(\'|\")\s*;/
		$v_3_56    = /\$CGI::VERSION\s*=\s*(\'|\")3.56(\'|\")\s*;/
		$v_3_55    = /\$CGI::VERSION\s*=\s*(\'|\")3.55(\'|\")\s*;/
		$v_3_54    = /\$CGI::VERSION\s*=\s*(\'|\")3.54(\'|\")\s*;/
		$v_3_53    = /\$CGI::VERSION\s*=\s*(\'|\")3.53(\'|\")\s*;/
		$v_3_52    = /\$CGI::VERSION\s*=\s*(\'|\")3.52(\'|\")\s*;/
		$v_3_51    = /\$CGI::VERSION\s*=\s*(\'|\")3.51(\'|\")\s*;/
		$v_3_50    = /\$CGI::VERSION\s*=\s*(\'|\")3.50(\'|\")\s*;/
	condition:
		PerlCGIModule and any of ($v*)
}
