rule CVE_2014_1875
{
//This rule was generated by: ./yargen -m Capture::Tiny -c CVE-2014-1875
	meta:
		component_name = "Capture-Tiny module for Perl"
		component_version = "before 0.24"
		custom_title = "Cspan Capture-tiny 0.20/0.21/0.22/0.23 Capture::Tiny privilege escalation"
		custom_level = "low"
		custom_description = "<p>The Capture::Tiny module before 0.24 for Perl allows local users to write to arbitrary files via a symlink attack on a temporary file.</p>"
	strings:
		$v_0_23    = /our\s+\$VERSION\s*=\s*(\'|\")0.23(\'|\")\s*;/
		$v_0_22    = /our\s+\$VERSION\s*=\s*(\'|\")0.22(\'|\")\s*;/
		$v_0_21    = /our\s+\$VERSION\s*=\s*(\'|\")0.21(\'|\")\s*;/
		$v_0_20    = /our\s+\$VERSION\s*=\s*(\'|\")0.20(\'|\")\s*;/
	condition:
		PerlCaptureTinyModule and any of ($v*)
}
