rule CVE_2015_3451
{
//This rule was generated by: ./yargen -m XML::LibXML -c CVE-2015-3451
	meta:
		component_name = "XML-LibXML module for Perl"
		component_version = "before 2.0119"
		custom_title = "XML::LibXML up to 2.118 _clone privilege escalation"
		custom_level = "medium"
		custom_description = "<p>The _clone function in XML::LibXML before 2.0119 does not properly set the expand_entities option, which allows remote attackers to conduct XML external entity (XXE) attacks via crafted XML data to the (1) new or (2) load_xml function.</p>"
	strings:
		$v_2_0118 = /\$VERSION\s*=\s*(\'|\")2.0118(\'|\")\s*;/
		$v_2_0117 = /\$VERSION\s*=\s*(\'|\")2.0117(\'|\")\s*;/
		$v_2_0116 = /\$VERSION\s*=\s*(\'|\")2.0116(\'|\")\s*;/
		$v_2_0115 = /\$VERSION\s*=\s*(\'|\")2.0115(\'|\")\s*;/
		$v_2_0114 = /\$VERSION\s*=\s*(\'|\")2.0114(\'|\")\s*;/
		$v_2_0113 = /\$VERSION\s*=\s*(\'|\")2.0113(\'|\")\s*;/
		$v_2_0112 = /\$VERSION\s*=\s*(\'|\")2.0112(\'|\")\s*;/
		$v_2_0111 = /\$VERSION\s*=\s*(\'|\")2.0111(\'|\")\s*;/
		$v_2_0110 = /\$VERSION\s*=\s*(\'|\")2.0110(\'|\")\s*;/
		$v_2_0109 = /\$VERSION\s*=\s*(\'|\")2.0109(\'|\")\s*;/
		$v_2_0108 = /\$VERSION\s*=\s*(\'|\")2.0108(\'|\")\s*;/
		$v_2_0107 = /\$VERSION\s*=\s*(\'|\")2.0107(\'|\")\s*;/
		$v_2_0106 = /\$VERSION\s*=\s*(\'|\")2.0106(\'|\")\s*;/
		$v_2_0105 = /\$VERSION\s*=\s*(\'|\")2.0105(\'|\")\s*;/
		$v_2_0104 = /\$VERSION\s*=\s*(\'|\")2.0104(\'|\")\s*;/
		$v_2_0103 = /\$VERSION\s*=\s*(\'|\")2.0103(\'|\")\s*;/
		$v_2_0102 = /\$VERSION\s*=\s*(\'|\")2.0102(\'|\")\s*;/
		$v_2_0101 = /\$VERSION\s*=\s*(\'|\")2.0101(\'|\")\s*;/
		$v_2_0100 = /\$VERSION\s*=\s*(\'|\")2.0100(\'|\")\s*;/
		$v_2_0019 = /\$VERSION\s*=\s*(\'|\")2.0019(\'|\")\s*;/
		$v_2_0018 = /\$VERSION\s*=\s*(\'|\")2.0018(\'|\")\s*;/
		$v_2_0017 = /\$VERSION\s*=\s*(\'|\")2.0017(\'|\")\s*;/
		$v_2_0016 = /\$VERSION\s*=\s*(\'|\")2.0016(\'|\")\s*;/
		$v_2_0015 = /\$VERSION\s*=\s*(\'|\")2.0015(\'|\")\s*;/
		$v_2_0014 = /\$VERSION\s*=\s*(\'|\")2.0014(\'|\")\s*;/
		$v_2_0013 = /\$VERSION\s*=\s*(\'|\")2.0013(\'|\")\s*;/
		$v_2_0012 = /\$VERSION\s*=\s*(\'|\")2.0012(\'|\")\s*;/
		$v_2_0011 = /\$VERSION\s*=\s*(\'|\")2.0011(\'|\")\s*;/
		$v_2_0010 = /\$VERSION\s*=\s*(\'|\")2.0010(\'|\")\s*;/
		$v_2_0009 = /\$VERSION\s*=\s*(\'|\")2.0009(\'|\")\s*;/
		$v_2_0008 = /\$VERSION\s*=\s*(\'|\")2.0008(\'|\")\s*;/
		$v_2_0007 = /\$VERSION\s*=\s*(\'|\")2.0007(\'|\")\s*;/
		$v_2_0006 = /\$VERSION\s*=\s*(\'|\")2.0006(\'|\")\s*;/
		$v_2_0005 = /\$VERSION\s*=\s*(\'|\")2.0005(\'|\")\s*;/
		$v_2_0004 = /\$VERSION\s*=\s*(\'|\")2.0004(\'|\")\s*;/
		$v_2_0003 = /\$VERSION\s*=\s*(\'|\")2.0003(\'|\")\s*;/
		$v_2_0002 = /\$VERSION\s*=\s*(\'|\")2.0002(\'|\")\s*;/
		$v_2_0001 = /\$VERSION\s*=\s*(\'|\")2.0001(\'|\")\s*;/
		$v_2_0000 = /\$VERSION\s*=\s*(\'|\")2.0000(\'|\")\s*;/
	condition:
		PerlXMLLibXMLModule and any of ($v*)
}
