rule CVE_2013_7284
{
//This rule was generated by: ./yargen -m RPC::PlServer -c CVE-2013-7284
	meta:
		component_name = "RPC-PlServer module for Perl"
		component_version = "0.2020 and earlier"
		custom_title = "Malcolm Nooning Pirpc up to 0.2020 RPC Module buffer overflow"
		custom_level = "medium"
		custom_description = "<p>The PlRPC module, possibly 0.2020 and earlier, for Perl uses the Storable module, which allows remote attackers to execute arbitrary code via a crafted request, which is not properly handled when it is deserialized.</p>"
	strings:
		$v_0_2020 = /\$RPC::PlServer::VERSION\s*=\s*(\'|\")0.2020(\'|\")\s*;/
		$v_0_2019 = /\$RPC::PlServer::VERSION\s*=\s*(\'|\")0.2019(\'|\")\s*;/
		$v_0_2018 = /\$RPC::PlServer::VERSION\s*=\s*(\'|\")0.2018(\'|\")\s*;/
		$v_0_2017 = /\$RPC::PlServer::VERSION\s*=\s*(\'|\")0.2017(\'|\")\s*;/
		$v_0_2016 = /\$RPC::PlServer::VERSION\s*=\s*(\'|\")0.2016(\'|\")\s*;/
		$v_0_2015 = /\$RPC::PlServer::VERSION\s*=\s*(\'|\")0.2015(\'|\")\s*;/
		$v_0_2014 = /\$RPC::PlServer::VERSION\s*=\s*(\'|\")0.2014(\'|\")\s*;/
		$v_0_2013 = /\$RPC::PlServer::VERSION\s*=\s*(\'|\")0.2013(\'|\")\s*;/
		$v_0_2012 = /\$RPC::PlServer::VERSION\s*=\s*(\'|\")0.2012(\'|\")\s*;/
		$v_0_2011 = /\$RPC::PlServer::VERSION\s*=\s*(\'|\")0.2011(\'|\")\s*;/
		$v_0_2010 = /\$RPC::PlServer::VERSION\s*=\s*(\'|\")0.2010(\'|\")\s*;/
		$v_0_2004 = /\$RPC::PlServer::VERSION\s*=\s*(\'|\")0.2004(\'|\")\s*;/
		$v_0_2003 = /\$RPC::PlServer::VERSION\s*=\s*(\'|\")0.2003(\'|\")\s*;/
		$v_0_2001 = /\$RPC::PlServer::VERSION\s*=\s*(\'|\")0.2001(\'|\")\s*;/
	condition:
		PerlRPCPlServerModule and any of ($v*)
}
