rule CVE_2011_3599
{
//This rule was generated by: ./yargen -m Crypt::DSA -c CVE-2011-3599
	meta:
		component_name = "Crypt-DSA module for Perl"
		component_version = "1.17 and earlier"
		custom_title = "Adam Kennedy Crypt-DSA up to 1.17 Crypt::DSA spoofing"
		custom_level = "medium"
		custom_description = "<p>The Crypt::DSA (aka Crypt-DSA) module 1.17 and earlier for Perl, when /dev/random is absent, uses the Data::Random module, which makes it easier for remote attackers to spoof a signature, or determine the signing key of a signed message, via a brute-force attack.</p>"
	strings:
		$v_1_17    = /\$VERSION\s*=\s*(\'|\")1.17(\'|\")\s*;/
		$v_1_16    = /\$VERSION\s*=\s*(\'|\")1.16(\'|\")\s*;/
		$v_0_15_01 = /\$VERSION\s*=\s*(\'|\")0.15_01(\'|\")\s*;/
		$v_0_14    = /\$VERSION\s*=\s*(\'|\")0.14(\'|\")\s*;/
		$v_0_13    = /\$VERSION\s*=\s*(\'|\")0.13(\'|\")\s*;/
		$v_0_12    = /\$VERSION\s*=\s*(\'|\")0.12(\'|\")\s*;/
		$v_0_11    = /\$VERSION\s*=\s*(\'|\")0.11(\'|\")\s*;/
		$v_0_10    = /\$VERSION\s*=\s*(\'|\")0.10(\'|\")\s*;/
		$v_0_03    = /\$VERSION\s*=\s*(\'|\")0.03(\'|\")\s*;/
		$v_0_02    = /\$VERSION\s*=\s*(\'|\")0.02(\'|\")\s*;/
		$v_0_01    = /\$VERSION\s*=\s*(\'|\")0.01(\'|\")\s*;/
	condition:
		PerlCryptDSAModule and any of ($v*)
}
