rule CVE_2014_4330
{
//This rule was generated by: ./yargen -m Data::Dumper -c CVE-2014-4330
	meta:
		component_name = "Data-Dumper module for Perl"
		component_version = "before 2.154"
		custom_title = "Data Dumper up to 2.151 Data::Dumper denial of service"
		custom_level = "low"
		custom_description = "<p>The Dumper method in Data::Dumper before 2.154, as used in Perl 5.20.1 and earlier, allows context-dependent attackers to cause a denial of service (stack consumption and crash) via an Array-Reference with many nested Array-References, which triggers a large number of recursive calls to the DD_dump function.</p>"
	strings:
		$v_2_151    = /\$VERSION\s*=\s*(\'|\")2.151(\'|\")\s*;/
		$v_2_145    = /\$VERSION\s*=\s*(\'|\")2.145(\'|\")\s*;/
		$v_2_143    = /\$VERSION\s*=\s*(\'|\")2.143(\'|\")\s*;/
		$v_2_139    = /\$VERSION\s*=\s*(\'|\")2.139(\'|\")\s*;/
		$v_2_136    = /\$VERSION\s*=\s*(\'|\")2.136(\'|\")\s*;/
		$v_2_135_07 = /\$VERSION\s*=\s*(\'|\")2.135_07(\'|\")\s*;/
		$v_2_135_02 = /\$VERSION\s*=\s*(\'|\")2.135_02(\'|\")\s*;/
		$v_2_135_01 = /\$VERSION\s*=\s*(\'|\")2.135_01(\'|\")\s*;/
		$v_2_131    = /\$VERSION\s*=\s*(\'|\")2.131(\'|\")\s*;/
		$v_2_130_03 = /\$VERSION\s*=\s*(\'|\")2.130_03(\'|\")\s*;/
		$v_2_12_02  = /\$VERSION\s*=\s*(\'|\")2.12_02(\'|\")\s*;/
		$v_2_12_01  = /\$VERSION\s*=\s*(\'|\")2.12_01(\'|\")\s*;/
		$v_2_128    = /\$VERSION\s*=\s*(\'|\")2.128(\'|\")\s*;/
		$v_2_127    = /\$VERSION\s*=\s*(\'|\")2.127(\'|\")\s*;/
		$v_2_126_01 = /\$VERSION\s*=\s*(\'|\")2.126_01(\'|\")\s*;/
		$v_2_126    = /\$VERSION\s*=\s*(\'|\")2.126(\'|\")\s*;/
		$v_2_125    = /\$VERSION\s*=\s*(\'|\")2.125(\'|\")\s*;/
		$v_2_124    = /\$VERSION\s*=\s*(\'|\")2.124(\'|\")\s*;/
		$v_2_123    = /\$VERSION\s*=\s*(\'|\")2.123(\'|\")\s*;/
		$v_2_122    = /\$VERSION\s*=\s*(\'|\")2.122(\'|\")\s*;/
		$v_2_121_20 = /\$VERSION\s*=\s*(\'|\")2.121_20(\'|\")\s*;/
		$v_2_121    = /\$VERSION\s*=\s*(\'|\")2.121(\'|\")\s*;/
		$v_2_101    = /\$VERSION\s*=\s*\$VERSION\s*=\s*(\'|\")2.101(\'|\")\s*;/
		$v_2_10     = /\$VERSION\s*=\s*\$VERSION\s*=\s*(\'|\")2.10(\'|\")\s*;/
		$v_2_09     = /\$VERSION\s*=\s*\$VERSION\s*=\s*(\'|\")2.09(\'|\")\s*;/
		$v_2_081    = /\$VERSION\s*=\s*\$VERSION\s*=\s*(\'|\")2.081(\'|\")\s*;/
		$v_2_08     = /\$VERSION\s*=\s*\$VERSION\s*=\s*(\'|\")2.08(\'|\")\s*;/
		$v_2_07     = /\$VERSION\s*=\s*\$VERSION\s*=\s*(\'|\")2.07(\'|\")\s*;/
		$v_2_06     = /\$VERSION\s*=\s*\$VERSION\s*=\s*(\'|\")2.06(\'|\")\s*;/
		$v_2_05     = /\$VERSION\s*=\s*\$VERSION\s*=\s*(\'|\")2.05(\'|\")\s*;/
		$v_2_04     = /\$VERSION\s*=\s*\$VERSION\s*=\s*(\'|\")2.04(\'|\")\s*;/
		$v_2_03     = /\$VERSION\s*=\s*\$VERSION\s*=\s*(\'|\")2.03(\'|\")\s*;/
		$v_2_02     = /\$VERSION\s*=\s*\$VERSION\s*=\s*(\'|\")2.02(\'|\")\s*;/
		$v_2_01     = /\$VERSION\s*=\s*\$VERSION\s*=\s*(\'|\")2.01(\'|\")\s*;/
		$v_2_00     = /\$VERSION\s*=\s*\$VERSION\s*=\s*(\'|\")2.00(\'|\")\s*;/
	condition:
		PerlDataDumperModule and any of ($v*)
}
