rule CVE_2014_1626
{
//This rule was generated by: ./yargen -m MARC::File::XML -c CVE-2014-1626
	meta:
		component_name = "MARC-File-XML module for Perl"
		component_version = "before 1.0.2"
		custom_title = "Galen Charlton Marc-xml 1.0/1.0.1 MARC::File::XML XXE"
		custom_level = "low"
		custom_description = "<p>XML External Entity (XXE) vulnerability in MARC::File::XML module before 1.0.2 for Perl, as used in Evergreen, Koha, perl4lib, and possibly other products, allows context-dependent attackers to read arbitrary files via a crafted XML file.</p>"
	strings:
		$v_1_0_1  = /\$VERSION\s*=\s*(\'|\")1.0.1(\'|\")\s*;/
		$v_1_0    = /\$VERSION\s*=\s*(\'|\")1.0(\'|\")\s*;/
	condition:
		PerlMARCFileXMLModule and any of ($v*)
}
