rule CVE_2012_1152
{
//This rule was generated by: ./yargen -m YAML::LibYAML -c CVE-2012-1152
	meta:
		component_name = "YAML-LibYAML module for Perl"
		component_version = "0.38"
		custom_title = "Perl YAML::LibYAML Module LibYAML/perl_libyaml.c Format String"
		custom_level = "medium"
		custom_description = "<p>Multiple format string vulnerabilities in the error reporting functionality in the YAML::LibYAML (aka YAML-LibYAML and perl-YAML-LibYAML) module 0.38 for Perl allow remote attackers to cause a denial of service (process crash) via format string specifiers in a (1) YAML stream to the Load function, (2) YAML node to the load_node function, (3) YAML mapping to the load_mapping function, or (4) YAML sequence to the load_sequence function.</p>"
	strings:
		$v_0_38     = /our\s+\$VERSION\s*=\s*(\'|\")0.38(\'|\")\s*;/
	condition:
		PerlYAMLLibYAMLModule and any of ($v*)
}
