rule CVE_2012_2451
{
//This rule was generated by: ./yargen -m Config::IniFiles -c CVE-2012-2451
	meta:
		component_name = "Config-IniFiles module for Perl"
		component_version = "before 2.71"
		custom_title = "Shlomi Fish Config-inifiles 2.70 ini Config::IniFiles privilege escalation"
		custom_level = "low"
		custom_description = "<p>The Config::IniFiles module before 2.71 for Perl creates temporary files with predictable names, which allows local users to overwrite arbitrary files via a symlink attack. NOTE: some of these details are obtained from third party information. NOTE: it has been reported that this might only be exploitable by writing in the same directory as the .ini file. If this is the case, then this issue might not cross privilege boundaries.</p>"
	strings:
		$v_2_70 = /\$VERSION\s*=\s*(\'|\")2.70(\'|\")\s*;/
		$v_2_69 = /\$VERSION\s*=\s*(\'|\")2.69(\'|\")\s*;/
		$v_2_68 = /\$VERSION\s*=\s*(\'|\")2.68(\'|\")\s*;/
		$v_2_67 = /\$VERSION\s*=\s*(\'|\")2.67(\'|\")\s*;/
		$v_2_66 = /\$VERSION\s*=\s*(\'|\")2.66(\'|\")\s*;/
		$v_2_65 = /\$VERSION\s*=\s*(\'|\")2.65(\'|\")\s*;/
		$v_2_64 = /\$VERSION\s*=\s*(\'|\")2.64(\'|\")\s*;/
		$v_2_63 = /\$VERSION\s*=\s*(\'|\")2.63(\'|\")\s*;/
		$v_2_62 = /\$VERSION\s*=\s*(\'|\")2.62(\'|\")\s*;/
		$v_2_61 = /\$VERSION\s*=\s*(\'|\")2.61(\'|\")\s*;/
		$v_2_60 = /\$VERSION\s*=\s*(\'|\")2.60(\'|\")\s*;/
		$v_2_59 = /\$VERSION\s*=\s*(\'|\")2.59(\'|\")\s*;/
		$v_2_58 = /\$VERSION\s*=\s*(\'|\")2.58(\'|\")\s*;/
		$v_2_57 = /\$VERSION\s*=\s*(\'|\")2.57(\'|\")\s*;/
		$v_2_56 = /\$VERSION\s*=\s*(\'|\")2.56(\'|\")\s*;/
		$v_2_55 = /\$VERSION\s*=\s*(\'|\")2.55(\'|\")\s*;/
		$v_2_54 = /\$VERSION\s*=\s*(\'|\")2.54(\'|\")\s*;/
		$v_2_53 = /\$VERSION\s*=\s*(\'|\")2.53(\'|\")\s*;/
		$v_2_52 = /\$VERSION\s*=\s*(\'|\")2.52(\'|\")\s*;/
		$v_2_51 = /\$VERSION\s*=\s*(\'|\")2.51(\'|\")\s*;/
		$v_2_50 = /\$VERSION\s*=\s*(\'|\")2.50(\'|\")\s*;/
	condition:
		PerlConfigIniFilesModule and any of ($v*)
}
