rule CVE_2011_3597
{
//This rule was generated by: ./yargen -m Digest -c CVE-2011-3597
	meta:
		component_name = "Digest module for Perl"
		component_version = "before 1.17"
		custom_title = "Gisle Aas Digest up to 1.16 digest new privilege escalation"
		custom_level = "medium"
		custom_description = "<p>Eval injection vulnerability in the Digest module before 1.17 for Perl allows context-dependent attackers to execute arbitrary commands via the new constructor.</p>"
	strings:
		$v_1_16 = /\$VERSION\s*=\s*(\'|\")1.16(\'|\")\s*;/
		$v_1_15 = /\$VERSION\s*=\s*(\'|\")1.15(\'|\")\s*;/
		$v_1_14 = /\$VERSION\s*=\s*(\'|\")1.14(\'|\")\s*;/
		$v_1_13 = /\$VERSION\s*=\s*(\'|\")1.13(\'|\")\s*;/
		$v_1_12 = /\$VERSION\s*=\s*(\'|\")1.12(\'|\")\s*;/
		$v_1_11 = /\$VERSION\s*=\s*(\'|\")1.11(\'|\")\s*;/
		$v_1_10 = /\$VERSION\s*=\s*(\'|\")1.10(\'|\")\s*;/
		$v_1_09 = /\$VERSION\s*=\s*(\'|\")1.09(\'|\")\s*;/
		$v_1_08 = /\$VERSION\s*=\s*(\'|\")1.08(\'|\")\s*;/
		$v_1_07 = /\$VERSION\s*=\s*(\'|\")1.07(\'|\")\s*;/
		$v_1_06 = /\$VERSION\s*=\s*(\'|\")1.06(\'|\")\s*;/
		$v_1_05 = /\$VERSION\s*=\s*(\'|\")1.05(\'|\")\s*;/
		$v_1_04 = /\$VERSION\s*=\s*(\'|\")1.04(\'|\")\s*;/
		$v_1_03 = /\$VERSION\s*=\s*(\'|\")1.03(\'|\")\s*;/
		$v_1_02 = /\$VERSION\s*=\s*(\'|\")1.02(\'|\")\s*;/
		$v_1_01 = /\$VERSION\s*=\s*(\'|\")1.01(\'|\")\s*;/
		$v_1_00 = /\$VERSION\s*=\s*(\'|\")1.00(\'|\")\s*;/
	condition:
		PerlDigestModule and any of ($v*)
}
