rule CVE_2013_4407
{
//This rule was generated by: ./yargen -m HTTP::Body -c CVE-2013-4407
	meta:
		component_name = "HTTP-Body module for Perl"
		component_version = "1.08"
		custom_title = "Http-body Project Perl 1.08 Temp File Name Handler HTTP::Body::Multipart privilege escalation"
		custom_level = "medium"
		custom_description = "<p>HTTP::Body::Multipart in the HTTP-Body 1.08, 1.17, and earlier module for Perl uses the part of the uploaded file's name after the first . character as the suffix of a temporary file, which makes it easier for remote attackers to conduct attacks by leveraging subsequent behavior that may assume the suffix is well-formed.</p>"
	strings:
		$v_1_17 = /\$HTTP::Body::VERSION\s*=\s*(\'|\")1.17(\'|\")\s*;/
		$v_1_16 = /\$HTTP::Body::VERSION\s*=\s*(\'|\")1.16(\'|\")\s*;/
		$v_1_15 = /\$HTTP::Body::VERSION\s*=\s*(\'|\")1.15(\'|\")\s*;/
		$v_1_14 = /\$HTTP::Body::VERSION\s*=\s*(\'|\")1.14(\'|\")\s*;/
		$v_1_12 = /\$HTTP::Body::VERSION\s*=\s*(\'|\")1.12(\'|\")\s*;/
		$v_1_11 = /\$HTTP::Body::VERSION\s*=\s*(\'|\")1.11(\'|\")\s*;/
		$v_1_10 = /\$HTTP::Body::VERSION\s*=\s*(\'|\")1.10(\'|\")\s*;/
		$v_1_09 = /\$HTTP::Body::VERSION\s*=\s*(\'|\")1.09(\'|\")\s*;/
		$v_1_08 = /\$HTTP::Body::VERSION\s*=\s*(\'|\")1.08(\'|\")\s*;/
		$v_1_07 = /our\s+\$VERSION\s*=\s*(\'|\")1.07(\'|\")\s*;/
		$v_1_06 = /our\s+\$VERSION\s*=\s*(\'|\")1.06(\'|\")\s*;/
		$v_1_05 = /our\s+\$VERSION\s*=\s*(\'|\")1.05(\'|\")\s*;/
		$v_1_04 = /our\s+\$VERSION\s*=\s*(\'|\")1.04(\'|\")\s*;/
		$v_1_03 = /our\s+\$VERSION\s*=\s*(\'|\")1.03(\'|\")\s*;/
		$v_1_02 = /our\s+\$VERSION\s*=\s*(\'|\")1.02(\'|\")\s*;/
		$v_1_01 = /our\s+\$VERSION\s*=\s*(\'|\")1.01(\'|\")\s*;/
		$v_1_00 = /our\s+\$VERSION\s*=\s*(\'|\")1.00(\'|\")\s*;/
	condition:
		PerlHTTPBodyModule and any of ($v*)
}
