private rule php_file
{
	meta:
			custom_description = "Private rule for identifying php files"
	strings:
			$start = /^<\?php/ nocase
	condition:
			$start
}

private rule xml_file
{
	meta:
			custom_description = "Private rule for identifying xml files"
	strings:
			$start = /^<\?xml/ nocase
	condition:
			$start
}

private rule PHPMailer
{
	meta:
			custom_description = "Private rule for identifying PHPMailer class"
	strings:
			$PHPMailer = "* @package PHPMailer"
	condition:
			$PHPMailer
}

private rule vBulletin
{
	// @product = "vBulletin"
	// @product_root = "../../"
	// @marker_file = "/core/includes/class_core.php"

	meta:
			custom_description = "Private rule for identifying vBulletin"
	strings:
			$package = /\*\s+\@package\s+vBulletin/
	condition:
			$package
}

private rule YiiFramework
{
	meta:
			custom_description = "Private rule for identifying YiiFramework"
	strings:
			$baseyii = /class BaseYii/ nocase
	condition:
			$baseyii
}

private rule RoundCubeWebmail
{
	meta:
			custom_description = "Private rule for identifying RoundCube Webmail"
	strings:
			$string = "Roundcube Webmail IMAP Client"
	condition:
			$string
}

private rule phpBB
{
	meta:
			custom_description = "Private rule for identifying phpBB forum software package"
	strings:
			$package = "* @package phpBB3"
	condition:
			$package
}

private rule CactiSuperlinksPlugin
{
	meta:
			custom_description = "Private rule for identifying Cacti Superlinks plugin"
	strings:
			$string = "http://docs.cacti.net/plugin:superlinks"
	condition:
			$string
}


private rule PerlEmailAddressModule
{
	meta:
			custom_description = "Private rule for identifying Perl Email::Address Module"
	strings:
			$string = /package\s+Email::Address\s*;/
	condition:
			$string
}

private rule PerlHTMLScrubberModule
{
	meta:
			custom_description = "Private rule for identifying Perl HTML::Scrubber Module"
	strings:
			$string = /package\s+HTML::Scrubber\s*;/
	condition:
			$string
}

private rule com_aicontactsafe
{
	// @product = "Joomla"
	// @product_root = "../../../"
	// @marker_file = "/administrator/components/com_aicontactsafe/aicontactsafe.xml"

	meta:
			custom_description = "Private rule for identifying aicontactsafe component from Joomla CMS"
	strings:
			$name = /<name>aiContactSafe<\/name>/ nocase
	condition:
			$name
}

private rule com_theatre
{
	// @product = "Joomla"
	// @product_root = "../../../"
	// @marker_file = "/administrator/components/com_theatre/theatre.xml"

	meta:
			custom_description = "Private rule for identifying com_theatre component from Joomla CMS"
	strings:
			$name = /<name>iC\s+agenda<\/name>/ nocase
	condition:
			$name
}

private rule Dotclear_CMS
{
	// @product = "Dotclear CMS"
	// @product_root = "../"
	// @marker_file = "/inc/prepend.php"

	meta:
			custom_description = "Private rule for indentifying Dotclear CMS"
	strings:
			$tizer = "# This file is part of Dotclear 2"
			$def = "define('DC_ROOT',"

	condition:
			$tizer and $def
}

private rule PerlDBDmysqlModule
{
//This rule was generated by: ./yargen -m DBD::mysql -c CVE-2015-8949
	meta:
		custom_description = "Private rule for identifying Perl DBD::mysql Module"
	strings:
		$package = /package\s+DBD::mysql\s*;/
	condition:
		$package
}

private rule PerlFileSpecModule
{
//This rule was generated by: ./yargen -m File::Spec -c CVE-2015-8607
	meta:
		custom_description = "Private rule for identifying Perl File::Spec Module"
	strings:
		$package = /package\s+File::Spec\s*;/
	condition:
		$package
}

private rule PerlXMLLibXMLModule
{
//This rule was generated by: ./yargen -m XML::LibXML -c CVE-2015-3451
	meta:
		custom_description = "Private rule for identifying Perl XML::LibXML Module"
	strings:
		$package = /package\s+XML::LibXML\s*;/
	condition:
		$package
}

private rule PerlDataDumperModule
{
//This rule was generated by: ./yargen -m Data::Dumper -c CVE-2014-4330
	meta:
		custom_description = "Private rule for identifying Perl Data::Dumper Module"
	strings:
		$package = /package\s+Data::Dumper\s*;/
	condition:
		$package
}

private rule PerlCaptureTinyModule
{
//This rule was generated by: ./yargen -m Capture::Tiny -c CVE-2014-1875
	meta:
		custom_description = "Private rule for identifying Perl Capture::Tiny Module"
	strings:
		$package = /package\s+Capture::Tiny\s*;/
	condition:
		$package
}

private rule PerlMARCFileXMLModule
{
//This rule was generated by: ./yargen -m MARC::File::XML -c CVE-2014-1626
	meta:
		custom_description = "Private rule for identifying Perl MARC::File::XML Module"
	strings:
		$package = /package\s+MARC::File::XML\s*;/
	condition:
		$package
}

private rule PerlProcDaemonModule
{
//This rule was generated by: ./yargen -m Proc::Daemon -c CVE-2013-7135
	meta:
		custom_description = "Private rule for identifying Perl Proc::Daemon Module"
	strings:
		$package = /package\s+Proc::Daemon\s*;/
	condition:
		$package
}

private rule PerlRPCPlServerModule
{
//This rule was generated by: ./yargen -m RPC::PlServer -c CVE-2013-7284
	meta:
		custom_description = "Private rule for identifying Perl RPC::PlServer Module"
	strings:
		$package = /package\s+RPC::PlServer\s*;/
	condition:
		$package
}

private rule PerlHTTPBodyModule
{
//This rule was generated by: ./yargen -m HTTP::Body -c CVE-2013-4407
	meta:
		custom_description = "Private rule for identifying Perl HTTP::Body Module"
	strings:
		$package = /package\s+HTTP::Body\s*;/
	condition:
		$package
}

private rule PerlModuleSignatureModule
{
//This rule was generated by: ./yargen -m Module::Signature -c CVE-2013-2145
	meta:
		custom_description = "Private rule for identifying Perl Module::Signature Module"
	strings:
		$package = /package\s+Module::Signature\s*;/
	condition:
		$package
}

private rule PerlHTMLEPModule
{
//This rule was generated by: ./yargen -m HTML::EP -c CVE-2012-6142
	meta:
		custom_description = "Private rule for identifying Perl HTML::EP Module"
	strings:
		$package = /package\s+HTML::EP\s*;/
	condition:
		$package
}

private rule PerlConfigIniFilesModule
{
//This rule was generated by: ./yargen -m Config::IniFiles -c CVE-2012-2451
	meta:
		custom_description = "Private rule for identifying Perl Config::IniFiles Module"
	strings:
		$package = /package\s+Config::IniFiles\s*;/
	condition:
		$package
}

private rule PerlYAMLLibYAMLModule
{
//This rule was generated by: ./yargen -m YAML::LibYAML -c CVE-2012-1152
	meta:
		custom_description = "Private rule for identifying Perl YAML::LibYAML Module"
	strings:
		$package = /package\s+YAML::LibYAML\s*;/
	condition:
		$package
}

private rule PerlCGIModule
{
//This rule was generated by: ./yargen -m CGI -c CVE-2012-5526
	meta:
		custom_description = "Private rule for identifying Perl CGI Module"
	strings:
		$package = /package\s+CGI\s*;/
	condition:
		$package
}

private rule PerlProcProcessTableModule
{
//This rule was generated by: ./yargen -m Proc::ProcessTable -c CVE-2011-4363
	meta:
		custom_description = "Private rule for identifying Perl Proc::ProcessTable Module"
	strings:
		$package = /package\s+Proc::ProcessTable\s*;/
	condition:
		$package
}

private rule PerlPARPackerModule
{
//This rule was generated by: ./yargen -m PAR::Packer -c CVE-2011-4114
	meta:
		custom_description = "Private rule for identifying Perl PAR::Packer Module"
	strings:
		$package = /package\s+PAR::Packer\s*;/
	condition:
		$package
}

private rule PerlCryptDSAModule
{
//This rule was generated by: ./yargen -m Crypt::DSA -c CVE-2011-3599
	meta:
		custom_description = "Private rule for identifying Perl Crypt::DSA Module"
	strings:
		$package = /package\s+Crypt::DSA\s*;/
	condition:
		$package
}

private rule PerlDataFormValidatorModule
{
//This rule was generated by: ./yargen -m Data::FormValidator -c CVE-2011-2201
	meta:
		custom_description = "Private rule for identifying Perl Data::FormValidator Module"
	strings:
		$package = /package\s+Data::FormValidator\s*;/
	condition:
		$package
}

private rule PerlFCGIModule
{
//This rule was generated by: ./yargen -m FCGI -c CVE-2011-2766
	meta:
		custom_description = "Private rule for identifying Perl FCGI Module"
	strings:
		$package = /package\s+FCGI\s*;/
	condition:
		$package
}

private rule PerlDigestModule
{
//This rule was generated by: ./yargen -m Digest -c CVE-2011-3597
	meta:
		custom_description = "Private rule for identifying Perl Digest Module"
	strings:
		$package = /package\s+Digest\s*;/
	condition:
		$package
}

private rule PerlHTMLTemplateProModule
{
//This rule was generated by: ./yargen -m HTML::Template::Pro -c CVE-2011-4616
	meta:
		custom_description = "Private rule for identifying Perl HTML::Template::Pro Module"
	strings:
		$package = /package\s+HTML::Template::Pro\s*;/
	condition:
		$package
}
